id: P002990
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:57.710567
source_metadata:
  id: bdr:W1KG23647
  title: ཡིག་རྨོངས་སེལ་བའི་སློབ་དེབ།
  author: ''
  volumes:
    ecbb7b6acd924852be45dd7ea76394bf:
      image_group_id: I1KG23679
      title: ''
      volume_number: 1
      total_pages: 0
    7fbac54dbcd9446ea42193dfa2c9dfc2:
      image_group_id: I1KG23680
      title: ''
      volume_number: 2
      total_pages: 0
    ebd18e454efb4342a65c8468f2109fe7:
      image_group_id: I1KG23681
      title: ''
      volume_number: 3
      total_pages: 0
    17c5c9d240c7441e91ea4366ecd71346:
      image_group_id: I1KG23682
      title: ''
      volume_number: 4
      total_pages: 56
      base_file: v001.txt
    cf9bffb533a643da892f8c0c935b1a6d:
      image_group_id: I1KG23683
      title: ''
      volume_number: 5
      total_pages: 0
    a0d345ffaedc482bbdc6109952d2fd43:
      image_group_id: I1KG23684
      title: ''
      volume_number: 6
      total_pages: 0
    68fc08aa8c2d496daf907a6d105c3097:
      image_group_id: I1KG23685
      title: ''
      volume_number: 7
      total_pages: 0
    8fe87e9251784d6fb0544deefcffb3fb:
      image_group_id: I1KG23686
      title: ''
      volume_number: 8
      total_pages: 0
    8c58541f47924b79a0635bc78bd33ae0:
      image_group_id: I1KG23687
      title: ''
      volume_number: 9
      total_pages: 0
    7ecb1dcce1a4466b95d55867c7b4825a:
      image_group_id: I1KG23688
      title: ''
      volume_number: 10
      total_pages: 0
    88f5a1c4e58347339e56b64f40e8ef36:
      image_group_id: I1KG23689
      title: ''
      volume_number: 11
      total_pages: 0
    91892b37e350421eac34cfa9206a63f8:
      image_group_id: I1KG23690
      title: ''
      volume_number: 12
      total_pages: 0
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
