id: IBA05E67D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:35:21+00:00'
last_modified: '2022-06-07T16:49:11.935383+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23647
  title: ཡིག་རྨོངས་སེལ་བའི་སློབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A7C:
      image_group_id: I1KG23679
      title: ''
      total_pages: 0
      order: 1
      base_file: 3A7C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
